import { useState, useMemo } from "react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import { Copy, Check, Download, ExternalLink, Eye, Code } from "lucide-react";
import { type Framework } from "../lib/api";

const LANG_MAP: Record<Framework, string> = {
  html: "html",
  tailwind: "html",
  react: "tsx",
  vue: "html",
};

const FILE_NAMES: Record<Framework, string> = {
  html: "index.html",
  tailwind: "index.html",
  react: "App.tsx",
  vue: "Component.vue",
};

function buildPreviewSrc(code: string, framework: Framework): string {
  if (framework === "tailwind") {
    return `<!doctype html><html><head><script src="https://cdn.tailwindcss.com"><\/script></head><body>${code}</body></html>`;
  }
  if (framework === "html") {
    return `<!doctype html><html><head></head><body>${code}</body></html>`;
  }
  return "";
}

function stackblitzUrl(code: string, framework: Framework): string {
  const files: Record<string, string> = {};
  if (framework === "react") {
    files["App.tsx"] = code;
    files["index.tsx"] = `import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App';\ncreateRoot(document.getElementById('root')!).render(<App />);`;
    files["index.html"] = `<!doctype html><html><body><div id="root"></div><script type="module" src="/index.tsx"><\/script></body></html>`;
  } else if (framework === "vue") {
    files["App.vue"] = code;
    files["main.ts"] = `import { createApp } from 'vue';\nimport App from './App.vue';\ncreateApp(App).mount('#app');`;
  }

  const params = new URLSearchParams({
    title: "Squint Output",
    description: "Generated by Squint",
    template: framework === "vue" ? "node" : "node",
  });

  const encoded = encodeURIComponent(JSON.stringify(files));
  return `https://stackblitz.com/fork/github?files=${encoded}&${params}`;
}

interface Props {
  code: string;
  framework: Framework;
}

type Tab = "code" | "preview";

export default function CodeViewer({ code, framework }: Props) {
  const [copied, setCopied] = useState(false);
  const [tab, setTab] = useState<Tab>("code");

  const canPreview = framework === "html" || framework === "tailwind";
  const previewSrc = useMemo(() => (canPreview ? buildPreviewSrc(code, framework) : ""), [code, framework]);

  const copy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([code], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = FILE_NAMES[framework];
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="rounded-xl overflow-hidden border border-gray-800 bg-gray-950 flex flex-col">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-4 py-2.5 bg-gray-900 border-b border-gray-800 gap-3 flex-wrap">
        <div className="flex items-center gap-1">
          <TabBtn active={tab === "code"} onClick={() => setTab("code")} icon={<Code className="w-3.5 h-3.5" />} label="Code" />
          {canPreview && (
            <TabBtn active={tab === "preview"} onClick={() => setTab("preview")} icon={<Eye className="w-3.5 h-3.5" />} label="Preview" />
          )}
          {!canPreview && (
            <a
              href={stackblitzUrl(code, framework)}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-gray-300 transition-colors px-2 py-1 rounded-md hover:bg-gray-800"
            >
              <ExternalLink className="w-3.5 h-3.5" /> StackBlitz
            </a>
          )}
        </div>

        <div className="flex items-center gap-1">
          <button
            onClick={download}
            className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-gray-200 transition-colors px-2 py-1 rounded-md hover:bg-gray-800"
          >
            <Download className="w-3.5 h-3.5" /> Download
          </button>
          <button
            onClick={copy}
            className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-gray-200 transition-colors px-2 py-1 rounded-md hover:bg-gray-800"
          >
            {copied ? (
              <><Check className="w-3.5 h-3.5 text-green-400" /><span className="text-green-400">Copied!</span></>
            ) : (
              <><Copy className="w-3.5 h-3.5" />Copy</>
            )}
          </button>
        </div>
      </div>

      {/* Content */}
      {tab === "code" ? (
        <div className="overflow-auto max-h-[520px] text-sm">
          <SyntaxHighlighter
            language={LANG_MAP[framework]}
            style={oneDark}
            customStyle={{ margin: 0, background: "transparent", padding: "1rem" }}
            showLineNumbers
            lineNumberStyle={{ color: "#4b5563", fontSize: "0.75rem" }}
          >
            {code}
          </SyntaxHighlighter>
        </div>
      ) : (
        <iframe
          srcDoc={previewSrc}
          title="Preview"
          sandbox="allow-scripts"
          className="w-full h-[520px] bg-white"
        />
      )}
    </div>
  );
}

function TabBtn({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: React.ReactNode; label: string }) {
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-1.5 text-xs px-2.5 py-1 rounded-md transition-colors ${
        active ? "bg-gray-800 text-gray-200" : "text-gray-500 hover:text-gray-300 hover:bg-gray-800"
      }`}
    >
      {icon} {label}
    </button>
  );
}
